apiVersion: 1
datasources:
  - name: TimescaleDB
    uid: POSTGRES_DS_UID
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: i40
    user: i40
    secureJsonData:
      password: i40pass
    isDefault: true
    jsonData:
      sslmode: disable
      postgresVersion: 14
      timescaledb: true